graphql:
  servlet:
    exception-handlers-enabled: true
server:
  port : 8090
spring:
  cloud:
    gcp:
      credentials:
        location: file:src/main/resources/key.json
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
axon:
  serializer:
    events: jackson